sudo: required

language: java

jdk: openjdk8

services:
  - docker

env:
  - NXF_VER=0.25.0

install:
  - curl -fsSL get.nextflow.io | bash
  - chmod +x nextflow
  - sudo mv nextflow /usr/local/bin/
  - wget https://github.com/singularityware/singularity/releases/download/2.3.1/singularity-2.3.1.tar.gz
  - tar xvf singularity-2.3.1.tar.gz
  - rm singularity-2.3.1.tar.gz
  - cd singularity-2.3.1
  - ./configure --prefix=/usr/local/singularity
  - sudo make install

script:
  - ./scripts/test_docker.sh
  - ./scripts/test_singularity.sh
