sudo: required

language: java

jdk: openjdk8

services:
  - docker

env:
  - NXF_VER=0.25.6 SGT_VER=2.3.1 PROFILE=docker
  - NXF_VER=0.25.6 SGT_VER=2.3.1 PROFILE=singularity

install: # Install Nextflow
  - "./scripts/install.sh --tool nextflow"

script:
  - "./scripts/test.sh --profile $PROFILE --install"
