sudo: required

language: java

jdk: openjdk8

node_js: "node"

services:
  - docker

env:
  - NXF_VER=0.30.2
  - NXF_VER=''

before_install:
- docker pull maxulysse/compile-latex:2.0

install:
  - curl -fsSL get.nextflow.io | bash
  - chmod +x nextflow
  - sudo mv nextflow /usr/local/bin/

script:
  - "nextflow run main.nf -profile test"
