sudo: required
language: java
jdk: openjdk8
services: docker

env:
  - NXF_VER=19.0.0.modules-draft10-SNAPSHOT
  - NXF_VER=''

before_install:
  - docker pull maxulysse/compile-latex:2.0

install:
  - curl -fsSL get.nextflow.io | bash
  - chmod +x nextflow
  - sudo mv nextflow /usr/local/bin/

script:
  - NXF_VER=19.0.0.modules-draft10-SNAPSHOT nextflow run main.nf -profile test
