sudo: required

language: java

jdk: openjdk8

services:
  - docker

env:
  - NXF_VER=0.27.0 TEX=sample.tex

install: # Install Nextflow
  - "./scripts/install.sh"

script:
  - "./scripts/test.sh --tex $TEX"
