sudo: required

language: java

jdk: openjdk8

services:
  - docker

env:
  - NXF_VER=0.24.2

install:
  - curl -fsSL get.nextflow.io | bash
  - chmod +x nextflow
  - sudo mv nextflow /usr/local/bin/

script:
  - ./script/test.sh
