sudo: required

language: java

jdk: openjdk8

services:
  - docker

env:
  - NXF_VER=0.25.6 SGT_VER=2.3.1 PROFILE=docker
  - NXF_VER=0.25.6 SGT_VER=2.3.1 PROFILE=singularity

install:
  - "./scripts/install.sh -t nextflow"
  - "./scripts/install.sh -t singularity"

script:
  - "./scripts/test.sh -p $PROFILE"
