sudo: required

language: java

jdk: openjdk8

services:
  - docker

install:
  - docker pull maxulysse/compile-beamer
  - curl -fsSL get.nextflow.io | bash

script:
  - ./nextflow run main.nf -with-docker -profile docker --tex sample.tex --theme SLL