version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8
        environment:
          NXF_VER: 0.25.0
          SGT_VER: 2.3.1
    steps:
      - run:
          name: Install Nextflow and Singularity
          command: |
            sudo apt-get install build-essential
            curl -fsSL get.nextflow.io | bash
            chmod +x nextflow
            sudo mv nextflow /usr/local/bin/
            wget https://github.com/singularityware/singularity/releases/download/$SGT_VER/singularity-$SGT_VER.tar.gz
            tar xvf singularity-$SGT_VER.tar.gz
            cd singularity-$SGT_VER
            ./configure --prefix=/usr/local
            make
            sudo make install
            cd ..
            rm -rf singularity-$SGT_VER*
      - run:
          name: Run tests
          command: |
            ./scripts/test_docker.sh
            ./scripts/test_singularity.sh
