version: 2
jobs:
  build:
    machine: true
    environment:
      NXF_VER: 0.25.6
      SGT_VER: 2.3.1
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Nextflow
          command: |
            curl -fsSL get.nextflow.io | bash
            chmod +x nextflow
            sudo mv nextflow /usr/local/bin/
      - run:
          name: Install Singularity
          command: |
            sudo apt-get install build-essential
            wget https://github.com/singularityware/singularity/releases/download/$SGT_VER/singularity-$SGT_VER.tar.gz
            tar xvf singularity-$SGT_VER.tar.gz
            cd singularity-$SGT_VER
            ./configure --prefix=/usr/local
            make
            sudo make install
            cd ..
            rm -rf singularity-$SGT_VER*
      - run:
          name: Run Docker test
          command: |
            ./scripts/test_docker.sh
      - run:
          name: Run Singularity test
          command: |
            ./scripts/test_singularity.sh
