version: 2
jobs:
  "nextflow-docker":
    docker:
      - image: circleci/openjdk:8
        environment:
          NXF_VER: 0.25.6
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Nextflow
          command: |
            ./scripts/install.sh -t nextflow
      # - run:
      #     name: Run Docker test
      #     command: |
      #       ./scripts/test.sh -p docker

  "nextflow-singularity":
    docker:
      - image: circleci/openjdk:8
        environment:
          NXF_VER: 0.25.6
          SGT_VER: 2.3.1
    steps:
      - checkout
      - run:
          name: Install Nextflow & Singularity
          command: |
            ./scripts/install.sh -t all
      # - run:
      #     name: Run Singularity test
      #     command: |
      #       ./scripts/test.sh -p singularity

workflows:
  version: 2
  build:
    jobs:
      - "nextflow-docker"
      - "nextflow-singularity"
