name: compile latex CI
# This workflow runs the pipeline with the minimal test dataset to check that it completes without any syntax errors
on:
  push:
    branches:
      - dev
  pull_request:
  release:
    types: [published]

env:
  NXF_ANSI_LOG: false

jobs:
  test:
    name: Run pipeline with test data
    runs-on: ubuntu-latest
    strategy:
      # HACK Remove after DSL2 rewrite is done
      fail-fast: false
      matrix:
        NXF_VER:
          - "21.10.3"
          - "latest-everything"
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v2

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v1
        with:
          version: "${{ matrix.NXF_VER }}"

      - name: Run pipeline with tests settings
        uses: Wandalen/wretry.action@v1.0.11
        with:
          command: nextflow run main.nf -profile test
          attempt_limit: 3
